<?php
/**
 * Roman Yurkhanov
 *
 * Email :: ferrumdp@gmail.com
 * Linkedin :: https://www.linkedin.com/in/roman-yurkhanov-322035122/
 *
 * Copyright 2024-present Roman Yurkhanov. All rights reserved.
 * See license.txt for license details.
 */

/** @var $block \RomanYurkhanov\Dealer\Block\Onepage\SuccessDealer */

/** @var \RomanYurkhanov\Dealer\ViewModel\Dealer $viewModel */

$viewModel = $block->getData('view_model');
$ordersItems = $block->getOrderItems();
?>

<div class="dealer-list">
    <?php foreach ($ordersItems as $item): ?>
        <?php
            $dealerId = $item->getProduct()->getData('dealer');

            $dealer = $viewModel->getDealerData($dealerId);
            $dealerLogo = $viewModel->getDealerLogoUrl($dealerId);

            $dealerDescriptionAttribute = $item->getProduct()->getData('dealer_description');

            $productName = $item->getProduct()->getName();
            $productUrl = $item->getProduct()->getProductUrl();
        ?>
        <div class="dealer-wrapper">
            <div class="dealer-logo">
                <?php if ($dealer->getLogo()) : ?>
                    <img src="<?= $block->escapeHtml($dealerLogo) ?>" width="140" height="140" alt="<?= $block->escapeHtml(__('Dealer logo')) ?>">
                <?php else : ?>
                    <img src="<?php echo $this->getViewFileUrl('RomanYurkhanov_Dealer::images/dealer-default.jpg'); ?>" width="140" height="140" alt="<?= $block->escapeHtml(__('Dealer default logo')) ?>"/>
                <?php endif; ?>
            </div>

            <ul class="dealer-info">
                <li>
                    <strong><?= $block->escapeHtml(__('Dealer:')) ?></strong>
                    <a href="<?= $block->getUrl('dealer/' . $dealer->getCode(), ['_secure' => true]) ?>"
                       title="<?= $block->escapeHtml($dealer['name']) ?>"
                    >
                        <?= $block->escapeHtml($dealer->getName()) ?>
                        (<?= $block->escapeHtml($dealer->getCode()) ?>)
                    </a>
                </li>

                <?php if ($dealerDescriptionAttribute) : ?>
                    <li>
                        <strong><?= $block->escapeHtml(__('Description:')) ?></strong>
                        <?php echo substr($dealerDescriptionAttribute, 0, 100); ?>
                        <?php if (strlen($dealerDescriptionAttribute) > 100) echo '...'; ?>
                    </li>
                <?php endif; ?>

                <li>
                    <strong><?= $block->escapeHtml(__('Product:')) ?></strong>
                    <a href="<?= $block->getUrl($productUrl, ['_secure' => true]) ?>"
                       title="<?= $block->escapeHtml($productName) ?>"
                    >
                        <?= $block->escapeHtml($productName) ?>
                    </a>
                </li>

                <?php /*
                    <?php if ($dealer->getDescription()) : ?>
                        <li>
                            <strong><?= $block->escapeHtml(__('Description:')) ?></strong>
                            <?php echo substr($dealer->getDescription(),0,100); ?>
                            <?php if(strlen($dealer->getDescription()) > 100) echo '...'; ?>
                        </li>
                    <?php endif; ?>
                 */ ?>
            </ul>
        </div>
    <?php endforeach; ?>
</div>
